import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, ShieldCheck, Clock3, Sparkles, MapPin, Star, Phone } from 'lucide-react';
import {services, areas, reviews} from '../content';

export default function Home(){ return <>
  <section className="hero">
    <img src="/images/pine-climber.webp" alt="CBX tree professional climbing a pine tree in Southwest Florida"/>
    <div className="heroShade"></div>
    <div className="heroContent"><span className="eyebrow">Naples-grown expertise • Nearly 15 years of experience</span><h1>Protecting Southwest Florida properties, one tree at a time.</h1><p>Professional tree removal, expert palm care and fast storm response—delivered with honest pricing, careful cleanup and owner-led service.</p><div className="heroActions"><Link className="button primary" to="/estimate">Request a Free Estimate <ArrowRight/></Link><a className="button ghost" href="tel:+12392380783"><Phone/> (239) 238-0783</a></div></div>
  </section>
  <section className="trust"><div><ShieldCheck/><strong>Licensed & Insured</strong></div><div><Clock3/><strong>Fast Scheduling</strong></div><div><Sparkles/><strong>Superior Cleanup</strong></div><div><CheckCircle2/><strong>Family Owned</strong></div></section>
  <section className="intro section"><div><span className="kicker">The CBX difference</span><h2>Your property deserves more than just a tree service.</h2></div><div><p>It deserves a team that protects your home, landscaping and peace of mind. Giovani is personally involved from the estimate through job completion, giving every project the attention of a local owner—not a corporate sales office.</p><Link className="textLink" to="/about">Meet Giovani <ArrowRight size={18}/></Link></div></section>
  <section className="services section alt"><div className="sectionHead"><span className="kicker">Complete tree care</span><h2>Services built around your property.</h2><p>From routine palm maintenance to difficult removals and storm cleanup, CBX handles the work safely and leaves the property clean.</p></div><div className="cards">{services.slice(0,6).map((s,i)=><Link className="serviceCard" to={`/services/${s.slug}`} key={s.slug}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.short}</p><ArrowRight/></Link>)}</div><div className="center"><Link className="button outline" to="/services">View All Services</Link></div></section>
  <section className="splitFeature section"><div className="featureImage"><img src="/images/poolside-palm-care.webp" alt="Tree care performed carefully beside a Naples pool"/></div><div className="featureText"><span className="kicker">Respect for your property</span><h2>Careful work in the spaces that matter most.</h2><p>Tree work often happens beside pools, roofs, driveways and established landscaping. We plan each project carefully, protect surrounding surfaces and clean up thoroughly when the work is complete.</p><ul><li><CheckCircle2/> Property protection</li><li><CheckCircle2/> Honest recommendations</li><li><CheckCircle2/> Clean, orderly job sites</li></ul><Link className="button primary" to="/gallery">See Our Work</Link></div></section>
  <section className="owner section alt"><div><img src="/images/giovani.webp" alt="Giovani, owner and founder of CBX Tree Service"/></div><div><span className="kicker">Meet the owner</span><h2>Local roots. Hands-on leadership.</h2><p>Born and raised in Naples, Giovani has spent nearly 15 years working with the trees and landscapes of Southwest Florida. He remains personally involved in every estimate and project, from the first conversation through final cleanup.</p><blockquote>“My goal is simple: give homeowners honest guidance, do the work safely and treat every property like it’s our own.”</blockquote><Link className="textLink" to="/about">Read our story <ArrowRight size={18}/></Link></div></section>
  <section className="reviews section"><div className="sectionHead"><span className="kicker">What customers say</span><h2>Trusted for quality, honesty and cleanup.</h2></div><div className="reviewGrid">{reviews.slice(0,3).map(r=><article className="reviewCard" key={r.name}><div className="stars">★★★★★</div><p>“{r.text}”</p><strong>{r.name}</strong><span>Google Review</span></article>)}</div><div className="center"><Link className="button outline" to="/reviews">Read More Reviews</Link></div></section>
  <section className="areas section dark"><div><span className="kicker light">Proudly serving Southwest Florida</span><h2>Rooted in Naples. Ready when you need us.</h2><p>Our current service area stretches from Bonita Springs south to Marco Island, with plans to grow north as CBX adds crews.</p></div><div className="areaList">{areas.map(a=><span key={a}><MapPin size={15}/>{a}</span>)}</div></section>
  <section className="cta section"><div><span className="kicker">Free estimates</span><h2>Let’s protect and improve your property.</h2><p>Tell us what you need and our team will follow up to schedule an estimate.</p></div><Link className="button primary" to="/estimate">Request Your Estimate <ArrowRight/></Link></section>
</> }
